module.exports = {
  CHE_COORDINATOR: 'CHE_COORDINATOR',
  CHE_FACULTY: 'CHE_FACULTY',
  CE_COORDINATOR: 'CE_COORDINATOR',
  CE_FACULTY: 'CE_FACULTY',
  CPE_COORDINATOR: 'CPE_COORDINATOR',
  CPE_FACULTY: 'CPE_FACULTY',
  ECE_COORDINATOR: 'ECE_COORDINATOR',
  ECE_FACULTY: 'ECE_FACULTY',
  IE_COORDINATOR: 'IE_COORDINATOR',
  IE_FACULTY: 'IE_FACULTY',
  MEM_COORDINATOR: 'MEM_COORDINATOR',
  MEM_FACULTY: 'MEM_FACULTY',
  ME_COORDINATOR: 'ME_COORDINATOR',
  ME_FACULTY: 'ME_FACULTY'
};
