node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'Node JS LTS') {
       sh 'npm install'
       sh 'export NODE_ENV=test'
       sh 'npm test'
     }
   }
   stage('heroku-deploy-staging') {
     sh '''
        # exit 1 on errors
        set -e
        # deal with remote
        echo "Checking if remote exists..."
        if ! git ls-remote heroku; then
          echo "Adding heroku remote..."
          git remote add heroku https://git.heroku.com/obqa-dlsu-web-api-staging.git
        fi
        # push only origin/master to heroku/master - will do nothing if
        # master doesn't change.
        echo "Updating heroku master branch..."
        git push heroku origin master
        '''     
   }
}